Repository umputun/remark42, pull requests merged in 2022-01, with the labels that each got.

#1222 Integrating Remark42 with Gatsby (documentation)
  site/src/docs/getting-started/integration-with-gatsby/index.md
  site/src/docs/nav.json
Labels: documentation

#1233 update docs link
  README.md
Labels: site

#1237 Add "invite your tg bot" note to documentation
  site/src/docs/configuration/telegram/index.md
Labels: documentation

#1240 Improve telegram notifications documentation
  site/src/docs/configuration/telegram/index.md
Labels: documentation

#1244 Improve backend and frontend development docs
  .gitignore
  site/src/docs/configuration/telegram/index.md
  site/src/docs/contributing/development/backend/index.md
  site/src/docs/contributing/development/frontend/index.md
  site/src/docs/contributing/development/index.md
  site/src/docs/contributing/translations/index.md
Labels: documentation

#1243 Log when deprecated and new args are set at the same time
  backend/app/cmd/cmd.go
  backend/app/cmd/server.go
  backend/app/cmd/server_test.go
  backend/app/main.go
Labels: backend

#1245 Improve doc on backend run without docker
  .gitignore
  site/src/docs/configuration/parameters/index.md
  site/src/docs/contributing/development/backend/index.md
Labels: documentation

#1246 Add QR API endpoint for Telegram auth and notifications
  backend/_example/memory_store/go.sum
  backend/app/rest/api/rest.go
  backend/app/rest/api/rest_public.go
  backend/app/rest/api/rest_public_test.go
  backend/app/rest/api/testdata/qr_test.png
  backend/go.mod
  backend/go.sum
  backend/remark.rest
  backend/vendor/github.com/skip2/go-qrcode/.gitignore
  backend/vendor/github.com/skip2/go-qrcode/.travis.yml
  backend/vendor/github.com/skip2/go-qrcode/LICENSE
  backend/vendor/github.com/skip2/go-qrcode/README.md
  backend/vendor/github.com/skip2/go-qrcode/bitset/bitset.go
  backend/vendor/github.com/skip2/go-qrcode/encoder.go
  backend/vendor/github.com/skip2/go-qrcode/go.mod
  backend/vendor/github.com/skip2/go-qrcode/qrcode.go
  backend/vendor/github.com/skip2/go-qrcode/reedsolomon/gf2_8.go
  backend/vendor/github.com/skip2/go-qrcode/reedsolomon/gf_poly.go
  backend/vendor/github.com/skip2/go-qrcode/reedsolomon/reed_solomon.go
  backend/vendor/github.com/skip2/go-qrcode/regular_symbol.go
  backend/vendor/github.com/skip2/go-qrcode/symbol.go
  backend/vendor/github.com/skip2/go-qrcode/version.go
  backend/vendor/modules.txt
Labels: backend
